- hosts: localhost
  tasks:
  - name: Loading pbvars.yaml config file
    include_vars:
      file: /etc/sensa/librenms/pbvars.yaml
      name: pbvars

  - name: remove librenms_syslog
    docker_container:
      name: librenms_syslog
      state: started
      restart: "yes"

  - name: remove librenms_cron
    docker_container:
      name: librenms_cron
      state: started
      restart: "yes"

  - name: remove librenms
    docker_container:
      name: librenms
      state: started
      restart: "yes"

  - name: remove librenms_db
    docker_container:
      name: librenms_db
      state: started
      restart: "yes"

  - name: remove librenms_oxidized
    docker_container:
      name: librenms_oxidized
      state: started
      restart: "yes"    

  - name: remove librenms_rrdcached
    docker_container:
      name: librenms_rrdcached
      state: started
      restart: "yes"

  - name: remove librenms_memcached
    docker_container:
      name: librenms_memcached
      state: started
      restart: "yes"

  - name: remove librenms_smtp
    docker_container:
      name: librenms_smtp
      state: started
      restart: "yes"